name: Go Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v3

      - name: 设置 Go 环境
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.3'

      - name: 运行测试
        run: go test ./...

      - name: 编译
        run: go build -o ghproxy-go ./main.go

      - name: 创建 ZIP 文件
        run: zip ghproxy-go-linux-64.zip ghproxy-go

      - name: 创建发布
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ghproxy-go v${{ github.ref_name }}  
          files: ghproxy-go-linux-64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
